version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python scripts/run_pipeline.py
      - aws s3 cp artifacts/model.pkl s3://$MODEL_S3_BUCKET/$MODEL_S3_MODEL_KEY
      - aws s3 cp artifacts/preprocessor.pkl s3://$MODEL_S3_BUCKET/$MODEL_S3_PREPROCESSOR_KEY

artifacts:
  files:
    - '**/*'
